#!/bin/bash


## If the first arg is 'install' install the dots...
if [[ "$1" == *"install"* ]]; then
	## Make sure user is root
	if [[ "$(id -u)" != "0" ]]; then
		echo "Must be root to install dots!!" 1>&2
		exit 1
	fi

	## Lemonbar
	cp ./lemonbar /usr/bin/bar

	## i3
	cp -rf ./i3 ${HOME}/.config/i3/

	## wal-set
	cp ./wal-set /usr/bin/wal-set

	## wal
	cp ./wal /usr/bin/wal

	## Xresources
	cp ./.Xresources ${HOME}/.Xresources

	## Xdefaults
	cp ./.Xdefaults ${HOME}/.Xdefaults
else
	## Lemonbar
	cp /usr/bin/bar ./lemonbar
	
	## i3
	cp -rf ${HOME}/.config/i3 ./
	
	## wal-set
	cp /usr/bin/wal-set ./wal-set
	
	## wal
	cp /usr/bin/wal ./wal

	## Xresources
	cp ${HOME}/.Xresources ./.Xresources

	## Xdefaults
	cp ${HOME}/.Xdefaults ./.Xdefaults
fi
